name: Bug
about: Reportar falha de comportamento
labels: ["bug"]
body:
  - type: textarea
    id: descricao
    attributes:
      label: Descrição
    validations:
      required: true
  - type: textarea
    id: reproducao
    attributes:
      label: Passos para reproduzir
    validations:
      required: true
  - type: textarea
    id: esperado
    attributes:
      label: Comportamento esperado
    validations:
      required: true
